import NavBar from "@/app/components/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "./components/Provider";
import ReactQueryProvider from "./components/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TextSaver",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          <Provider>
            <header>
              <NavBar />
            </header>
            <main style={{ marginTop: "4rem" }}>{children}</main>
          </Provider>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
